const GLOBAL = require("./constaint");

const endUrls = {
  diet: `${GLOBAL.BASE_URL}api/offer`,
  productOffer: `${GLOBAL.BASE_URL}api/ProductOffers`,
  bloodOffer: `${GLOBAL.BASE_URL}api/BloodtestOffers`,
  cartOffer: `${GLOBAL.BASE_URL}api/CartOffers`,
  btOffer: `${GLOBAL.BASE_URL}api/BloodtestOffers`,
  cartOffer: `${GLOBAL.BASE_URL}api/CartOffers`,
  // login: `${GLOBAL.BASE_URL}api/v2/mobile/check`,
  login: `${GLOBAL.BASE_URL}api/v3/email/check`,

  // login: `${GLOBAL.BASE_URL}api/v2/mobile/check`, // new
  // otp: `${GLOBAL.BASE_URL}api/otp/`,
  otp: `${GLOBAL.BASE_URL}api/v3/otp/verifyOtp`,
  profilecomplete: `${GLOBAL.BASE_URL}api/v3/login-profile-complete`,
  getprofilenew: `${GLOBAL.BASE_URL}api/v2/getprofile`,

  homePlan: `${GLOBAL.BASE_URL}api/plans`,
  menuCategory: `${GLOBAL.BASE_URL}api/productcategory`,
  homeIcone: `${GLOBAL.BASE_URL}api/homepagecategory`,
  secondCategory: `${GLOBAL.BASE_URL}api/secondhomepagecategory`,
  getAiCategory: `${GLOBAL.BASE_URL}api/v2/getaihomepagecategorydata`,
  homeApi: `${GLOBAL.BASE_URL}api/homepage`,
  jumbelCate: `${GLOBAL.BASE_URL}api/jumblecat/`,
  getfooter: `${GLOBAL.BASE_URL}api/getfooter/`,
  productCat: `${GLOBAL.BASE_URL}api/productcat/`,
  proDuctdetial: `${GLOBAL.BASE_URL}api/productdetails/`,
  medicalhistory: `${GLOBAL.BASE_URL}api/medicalhistory/`,
  addtocart: `${GLOBAL.BASE_URL}api/addtocart`,
  deleteaddress: `${GLOBAL.BASE_URL}api/deleteaddress/`,
  addaddress: `${GLOBAL.BASE_URL}api/addaddress`,
  editaddress: `${GLOBAL.BASE_URL}api/editaddress/`,
  updateaddress: `${GLOBAL.BASE_URL}api/updateaddress`,
  getalladdress: `${GLOBAL.BASE_URL}api/getalladdress`,
  getcartlist: `${GLOBAL.BASE_URL}api/getcartlist`,
  getcartcount: `${GLOBAL.BASE_URL}api/getcartcount`,
  removecart: `${GLOBAL.BASE_URL}api/removecart/`,
  addquantity: `${GLOBAL.BASE_URL}api/addquantity/`,
  subtractquantity: `${GLOBAL.BASE_URL}api/subtractquantity/`,
  removeBonus: `${GLOBAL.BASE_URL}api/remoove-applyknectt`,
  removeWallet: `${GLOBAL.BASE_URL}api/removeWalletAmount`,
  features: `${GLOBAL.BASE_URL}api/features/`,
  updateprofile: `${GLOBAL.BASE_URL}api/updateprofile`,
  getprofile: `${GLOBAL.BASE_URL}api/getprofile`,

  savecontactus: `${GLOBAL.BASE_URL}api/savecontactus`,
  ifalreadyaffiliate: `${GLOBAL.BASE_URL}api/ifalreadyaffiliate`,
  getaffiliatetext: `${GLOBAL.BASE_URL}api/getaffiliatetext`,
  saveaffiliate: `${GLOBAL.BASE_URL}api/saveaffiliate`,
  createOrder: `${GLOBAL.BASE_URL}api/createorder`,
  getrazorpaydetails: `${GLOBAL.BASE_URL}api/getrazorpaydetails`,
  updateaddresstoorder: `${GLOBAL.BASE_URL}api/updateaddresstoorder`,
  getsearchproducts: `${GLOBAL.BASE_URL}api/getsearchproducts`,
  paymentstart: `${GLOBAL.BASE_URL}api/paymentstart`,
  updatepaymentid: `${GLOBAL.BASE_URL}api/updatepaymentid`,
  myorders: `${GLOBAL.BASE_URL}api/myorders`,
  orderDetail: `${GLOBAL.BASE_URL}api/completeorderdetails/`,
  getnotification: `${GLOBAL.BASE_URL}api/getnotification`,
  policy: `${GLOBAL.BASE_URL}api/privacypolicy`,
  policies: `${GLOBAL.BASE_URL}api/getpolicies/`,
  getdisorder: `${GLOBAL.BASE_URL}api/getdisorder`,
  sendemailotp: `${GLOBAL.BASE_URL}api/sendemailotp`,
  verifyemailotp: `${GLOBAL.BASE_URL}api/verifyemailotp`,
  getminorailment: `${GLOBAL.BASE_URL}api/getminorailment`,
  applyknectt: `${GLOBAL.BASE_URL}api/applyknectt`,
  getallcity: `${GLOBAL.BASE_URL}api/getallcity`,
  saverating: `${GLOBAL.BASE_URL}api/saverating`,
  insertbodyprofile: `${GLOBAL.BASE_URL}api/insertbodyprofile`,
  gloabalurl: `${GLOBAL.BASE_URL}api/`,
  endAplireQ: `${GLOBAL.BASE_URL}`,
  medicalDisclaimer: `${GLOBAL.BASE_URL}api/getmedicaldisclaimer`,
  API_NAME_GET_SEARCH_LIST: `${GLOBAL.BASE_URL}api/getsearchlist`,
  API_NAME_ADD_BLOOD_TEST_TO_CART: `${GLOBAL.BASE_URL}api/addbloodtesttocart`,
  API_NAME_GET_TIME_SLOT: `${GLOBAL.BASE_URL}api/gettimeslot`,
  PAYMENT_STATUS: `${GLOBAL.BASE_URL}api/payment-status`,
  DEVICE_ATTACH: `${GLOBAL.BASE_URL}api/devices/attach`,
  DELETE_ACCOUNT: `${GLOBAL.BASE_URL}api/delete-customer-account`,
  STATES_API: `${GLOBAL.BASE_URL}api/getallstate`,
  REMOVE_CART_ITEM: `${GLOBAL.BASE_URL}api/cancelorder-razaorpay-refund-itemwise`,
  CHECK_BODY_MATCH: `${GLOBAL.BASE_URL}api/checkBodyMatchProduct`,
  PRE_HOMEPAGE_DATA: `${GLOBAL.BASE_URL}api/get-prehome-data`,
  OFFERING_DATA:`${GLOBAL.BASE_URL}api/get-offerings-data`
};
export default endUrls;
